### ISSUE TITLE
'editmoney' command throws Error on spaces

### ISSUE THREAD

**Issue by comjun04** [wonderlandpark/wonderbot#18]
<한국어>
`돈수정` 명령어를 사용할 때 인수에 띄어쓰기가 2개 이상 들어가 있으면 오류납니다.

\<English\>
`editmoney` command (owner only command) throws Error when arguments has two or more spaces.
![Capture+_2020-03-02-22-38-22](https://user-images.githubusercontent.com/30339539/75681352-bfde6000-5cd6-11ea-861f-cbd3ef5752b9.png)
입력한 값 / Input: 
> ..돈수정 set&nbsp;&nbsp;@유저멘션 100000

(띄어쓰기 2개 / 2 spaces)

오류 로그 / Error Log:
![Screenshot_2020-03-02-22-46-16](https://user-images.githubusercontent.com/30339539/75681855-c3261b80-5cd7-11ea-8366-c24dffd0163f.png)
![Screenshot_2020-03-02-22-46-33](https://user-images.githubusercontent.com/30339539/75681865-c7523900-5cd7-11ea-96a0-e3df6395e7fd.png)

```
2020/03/02 10:33:27 comjun04#5963 : ..돈수정 set  <@393674169243402240> 100000
Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'field list'
    at Query.Sequence._packetToError (/data/data/com.termux/files/home/wonderbot/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/data/data/com.termux/files/home/wonderbot/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/data/data/com.termux/files/home/wonderbot/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/data/data/com.termux/files/home/wonderbot/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/data/data/com.termux/files/home/wonderbot/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/data/data/com.termux/files/home/wonderbot/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/data/data/com.termux/files/home/wonderbot/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/data/data/com.termux/files/home/wonderbot/node_modules/mysql/lib/Connection.js:525:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:325:12)
    at readableAddChunk (_stream_readable.js:300:11)
    at Socket.Readable.push (_stream_readable.js:234:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
    --------------------
    at Protocol._enqueue (/data/data/com.termux/files/home/wonderbot/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/data/data/com.termux/files/home/wonderbot/node_modules/mysql/lib/Connection.js:201:25)
    at /data/data/com.termux/files/home/wonderbot/node_modules/knex/lib/dialects/mysql/index.js:135:18
    at Promise._execute (/data/data/com.termux/files/home/wonderbot/node_modules/bluebird/js/release/debuggability.js:411:9)
    at Promise._resolveFromExecutor (/data/data/com.termux/files/home/wonderbot/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/data/data/com.termux/files/home/wonderbot/node_modules/bluebird/js/release/promise.js:103:10)
    at Client_MySQL._query (/data/data/com.termux/files/home/wonderbot/node_modules/knex/lib/dialects/mysql/index.js:129:12)
    at Client_MySQL.query (/data/data/com.termux/files/home/wonderbot/node_modules/knex/lib/client.js:165:17)
    at Runner.query (/data/data/com.termux/files/home/wonderbot/node_modules/knex/lib/runner.js:135:36)
    at /data/data/com.termux/files/home/wonderbot/node_modules/knex/lib/runner.js:39:23
    at tryCatcher (/data/data/com.termux/files/home/wonderbot/node_modules/bluebird/js/release/util.js:16:23)
    at /data/data/com.termux/files/home/wonderbot/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/data/data/com.termux/files/home/wonderbot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/data/data/com.termux/files/home/wonderbot/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/data/data/com.termux/files/home/wonderbot/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/data/data/com.termux/files/home/wonderbot/node_modules/bluebird/js/release/promise.js:649:10) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'NaN' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "update `users` set `money` = NaN where `id` = '393674169243402240'"
}
```

**Comment by wonderlandpark** [comment]
관리자 명령어이기 때문에 굳이 고칠필요 없을거 같네요. 제가 잘못칠 확률은 별로 없는거 같아서
다른 의견 있다면 새로 이슈 남겨주세요

**Comment by wonderlandpark** [comment]
나중에 시간 나면 고칠게요
